sudo: required
services:
  - docker

before_install:
  - docker build -t adriandomin/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t adriandomin/multi-client ./client
  - docker build -t adriandomin/multi-nginx ./nginx
  - dcoekr build -t adriandomin/multi-server ./server
  - docker build -t adriandomin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hun
  - docker push adriandomin/multi-client
  - docker push adriandomin/multi-nginx
  - docker push adriandomin/multi-server
  - docker push adriandomin/multi-worker
