sudo: required
services:
  - docker

before_install:
  - docker build -t easyhne/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true easyhne/react-test npm run test

after_success:
  - docker build -t easyhne/multi-client ./client
  - docker build -t easyhne/multi-nginx ./nginx
  - dcoekr build -t easyhne/multi-server ./server
  - docker build -t easyhne/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hun
  - docker push easyhne/multi-client
  - docker push easyhne/multi-nginx
  - docker push easyhne/multi-server
  - docker push easyhne/multi-worker
